# Generated by Django 5.1.4 on 2025-11-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_empleado_contrato_remove_empleado_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='codigo_qr',
        ),
    ]
